### ISSUE TITLE
Support CRS in ISO XML

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/ckanext-publicamundi#108]

**Comment by kalxas** [comment]
INSPIRE supported coordinate systems:
http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.1.pdf (page 68)

List of EPSG codes:
https://github.com/OSGeo/proj.4/blob/master/nad/epsg

OWSLib support:
https://github.com/kalxas/OWSLib/commit/ae6589b98b5c0456a360d85a29b4bfa37f402646

**Comment by drmalex07** [comment]
@kalxas I think this is complete (owslib dependency, schema, widgets).
