### ISSUE TITLE
Protect against XXE libxml vulnerability

### ISSUE THREAD

**Issue by drmalex07** [PublicaMundi/ckanext-publicamundi#155]
Ensure no external (XXE) entities are resolved while parsing XML streams

**Comment by smanousopoulos** [comment]
We need to make sure everytime an XML is parsed from an external source an XML parser with resolve_entities=False should be passed

parser = etree.XMLParser(resolve_entities=False)

etree.fromstring(e, parser)
etree.parse(f, parser)

**Comment by drmalex07** [comment]
Fixed. Tested against common injection payloads
