### ISSUE TITLE
Translations missing from CKAN API

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/ckanext-publicamundi#161]
Some group translations fail to work from the API.
e.g. 
http://web.dev.publicamundi.eu/api/3/action/term_translation_show?lang_codes=el&terms=Geoscientific%20Information
works fine for el.
http://web.dev.publicamundi.eu/api/3/action/term_translation_show?lang_codes=el&terms=Climatology%20Meteorology%20Atmosphere
does not.

Thoughts?

**Comment by kalxas** [comment]
ok, this one works:
http://web.dev.publicamundi.eu/api/3/action/term_translation_show?lang_codes=el&terms=Climatology%20-%20Meteorology%20-%20Atmosphere
which means we need to use those names:

https://github.com/PublicaMundi/labs.geodata.gov.gr/blob/devel/deploy/files/groups/ckan/initialize/topics.csv

**Comment by smanousopoulos** [comment]
Yes, the group names we have translated are the ones found here http://catalog.publicamundi.eu/el/group

**Comment by kalxas** [comment]
@jkouvar we need to change the titles in the application to include dashes (-) so they can be translated from the CKAN API. Unfortunately, adding new fields in the Groups csv would also create new icons in the UI, which we want to avoid.
