### ISSUE TITLE
Raster importer - what?

### ISSUE THREAD

**Issue by howff** [PublicaMundi/ckanext-publicamundi#232]
"Provide processing and services for raster-based spatial resources" - sounds good!

First, configuration. The doc says

The docs says ckanext.publicamundi.rasterstorer.wcst_import_url = http://myRasdamanMachine:42000
but what is that?
The doc does not say ckanext.publicamundi.rasterstorer.url but that's in the .ini file
what is that?

Now, README-raster.md says "Extension that allows raster files to be imported into a WCST service. The extension allows any gdal raster formats (GeoTIFF, JPEG2000 etc) and GML raster files."
What does that even mean?

It doesn't mention rasdaman but I believe that it relies on rasdaman, is that right?

What does 'imported into a WCST service' mean?

How do I use it?

I am imagining that I can upload rasters via the ckan/publicamundi web GUI and they get stored in rasdaman, then I can use the web gui to search for them, and do raster analytics somehow?

**Comment by kalxas** [comment]
This line
```ckanext.publicamundi.rasterstorer.wcst_import_url = http://myRasdamanMachine:42000```
is needed in the configuration ini file to point to the rasdaman endpoint that handles the WCST requests.
The user can upload an image from the UI, a WCST request is submitted to rasdaman and the image gets ingested into rasdaman. Then WMS and WCS services are available for that dataset.
