### ISSUE TITLE
Vector importer - what?

### ISSUE THREAD

**Issue by howff** [PublicaMundi/ckanext-publicamundi#233]
"The publicamundi_vector plugin allows users to upload vector geospatial data, and store and publish through OGC services." - sound great!

What exactly does this do and how do I use it?

**Comment by kalxas** [comment]
You need to install geoserver, then configure the settings.ini file to point to the geoserver instance.
Once you upload a vector layer, this will be sent to postgis datastore and geoserver will be configured to publish this new layer through WMS, WFS.
