### ISSUE TITLE
Automate groups creation process (plus upload of icons)

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/ckanext-publicamundi#67]
Icons located at /var/local/ckan/default/files/storage/uploads/group/

**Comment by drmalex07** [comment]
Creation of groups (i.e topics and organizations) is moved under `labs.geodata.gov.gr` deployment. 

More can be found at:
https://github.com/PublicaMundi/labs.geodata.gov.gr/blob/master/deploy/import-ckan-groups.yml
