### ISSUE TITLE
Allow datastore API functions (datastore_upsert, datastore_delete) to access _id column

### ISSUE THREAD

**Issue by smanousopoulos** [PublicaMundi/ckanext-publicamundi#98]
This can be useful when dealing with resources that don't have a unique key or one just hasn't been set. It can be implemented by passing an explicit parameter in the parameters dictionary in order not to break current functionality.

**Comment by drmalex07** [comment]
This is addressed in a new branch `datastore-allow-update-with-id` under `PublicaMundi/ckan`.
See more at https://github.com/PublicaMundi/ckan/commit/c1cbb2d0ceaf4b12f373288e6f5b33e743a71122
